### ISSUE TITLE
Não ta funcionando

### ISSUE THREAD

**Issue by Caioww** [tamarac/bbb21-autovote#1]
Não está lendo o captcha, bora arrumar isso ai pra votar na Karol

**Comment by jpgutti** [comment]
Não existe nada no codigo que resolva o captcha

**Comment by tamarac** [comment]
> Não está lendo o captcha, bora arrumar isso ai pra votar na Karol

Não tem nada que identifique as imagens do captcha do google, para isso é necessário envolver uma ia. Comigo funciona colocando um sleep de 60 segundos ( ele nao pede para verificar as imagens), caso o seu ja tenha "bloqueado" terá q esperar uns minutos e tentar novamente.
